//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSale.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesDetails
    {
        public long SalesID { get; set; }
        public Nullable<long> CustID { get; set; }
        public Nullable<decimal> GrossTotal { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
