//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSale.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AlertResults
    {
        public long ID { get; set; }
        public string Alert { get; set; }
        public string Tablename { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ResultID { get; set; }
    }
}
